### ISSUE TITLE
Warning messages shown on SimpleBrowse example

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Alfresco/alfresco-php-sdk#12]
```
See attached screen shot for warnings shown when viewing SimpleBrowse example.

```

Original issue reported on code.google.com by `rwether...@gmail.com` on 29 Nov 2011 at 4:37

Attachments:
- [SimpleBrowseWarnings.png](https://storage.googleapis.com/google-code-attachments/alfresco-php-sdk/issue-12/comment-0/SimpleBrowseWarnings.png)

**Comment by ghost** [comment]
Repository no longer supported. Archiving repository and closing the tickets.
