### ISSUE TITLE
Error with cookies in mediawiki

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Alfresco/alfresco-php-sdk#18]
```
What steps will reproduce the problem?
1. Get a working LAMP with mediawiki without any error with cookies
2. Install and configure alfresco-php-sdk
3. Log with any user in mediawiki and I get this error:
"Login error
MyWiki uses cookies to log in users. You have cookies disabled. Please enable 
them and try again."
4. If I disable alfresco-php-sdk it works perfectly.


What version of the product are you using? On what operating system?
I'm using LAMP (Apache and mediawiki app from bitnami.org with Ubuntu 11.10 
(x86 version).

```

Original issue reported on code.google.com by `manuel.l...@gmail.com` on 10 Jan 2012 at 9:05

Attachments:
- [LocalSettings.php](https://storage.googleapis.com/google-code-attachments/alfresco-php-sdk/issue-18/comment-0/LocalSettings.php)
- [httpd.conf](https://storage.googleapis.com/google-code-attachments/alfresco-php-sdk/issue-18/comment-0/httpd.conf)
- [php.ini](https://storage.googleapis.com/google-code-attachments/alfresco-php-sdk/issue-18/comment-0/php.ini)

**Comment by ghost** [comment]
Repository no longer supported. Archiving repository and closing the tickets.
