### ISSUE TITLE
error in running php TutorialOne 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Alfresco/alfresco-php-sdk#22]
```
i tried to run the code of php Tutorial One but it give me following error

Fatal error: Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: 
Couldn't load from 
'https://my.alfresco.com:0443/share/alfresco/api/AuthenticationService?wsdl' 


i made an account on cloud and give the url above to access wsdl but alfter 
login server got fail..... 

please help me out to execute the simple tutorial one code
see attachments as well 


```

Original issue reported on code.google.com by `rahma.na...@rolustech.com` on 2 Oct 2014 at 10:11

**Comment by Mirdrack** [comment]
I'm very interested in collaborate with this repo, could somebody guide me with this?
I have the same problem, SOAP fails and if I'm going throught the browser it ask me for the credentials but my default credentials doesn't work.
Hope somebody can help me, thanks in advance

**Comment by SaidMarar** [comment]
it's 2016 almost 2017 no one answer ... i have same problem please someone help

**Comment by ghost** [comment]
Repository no longer supported. Archiving repository and closing the tickets.
