### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by harlangray** [Alfresco/alfresco-php-sdk#23]
What is wrong with this? The links to guides not working. Nothing is working.

**Comment by Haikuch** [comment]
same problem, any solution? Wehre can i find the tutorial for PHP implementation? Or Docu?

**Comment by ciencia** [comment]
[WayBackMachine](http://web.archive.org/web/20130702160047/http://code.google.com/p/alfresco-php-sdk/w/list) to the wiki hosted on code.google.com

---

Edit: I've just found that they're on the [wiki branch](https://github.com/Alfresco/alfresco-php-sdk/tree/wiki):

**Comment by ghost** [comment]
Repository no longer supported. Archiving repository and closing the tickets.
