### ISSUE TITLE
A Reflected XSS vulnerability in this sdk

### ISSUE THREAD

**Issue by jgj212** [Alfresco/alfresco-php-sdk#25]
Hello:
I found a Reflected XSS vulnerability in this sdk.

The vulnerability exists due to insufficient filtration of user-supplied data in 'title' HTTP _REQUEST parameter that will be passed to “alfresco-php-sdk-master/mediawiki-integration/source/php/alfresco-integration/login/AlfrescoLogin.php”. The infected source code is line 6 and line 244,  there is no protection on $_REQUEST["title"] before writing it to the response html; If $_REQUEST["title"] contains evil js code, line 244 will trigger untrusted code to be excuted on the browser side.
>
![code1](https://cloud.githubusercontent.com/assets/1484292/23264360/07c651b4-fa1c-11e6-888f-cb16179f0945.png)
![code2](https://cloud.githubusercontent.com/assets/1484292/23264414/313d20fe-fa1c-11e6-9201-426ac4e377ae.png)

So if a attacker construct a special url as follow and send it to a victim, when the victim click the url, the code which is contained in the url will be executed on the victim's browser side to do some evil.
http://your-web-root/alfresco-php-sdk-master/mediawiki-integration/source/php/alfresco-integration/login/AlfrescoLogin.php?title="><script>alert(1);</script><"

The follow screenshot is the result to click the upper url ( win7 sp1 x64 + firefox 51.0.1 32bit ):
>
![sc](https://cloud.githubusercontent.com/assets/1484292/23264844/bcc9d67a-fa1d-11e6-80d5-68e1eeeea147.png)

Discoverer: ADLab of Venustech

**Comment by ghost** [comment]
Repository no longer supported. Archiving repository and closing the tickets.
