### ISSUE TITLE
PHP sends incorrect complexType

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Alfresco/alfresco-php-sdk#5]
```
I'm not sure if schemas have changed since the release of the 2.1 php 
library or are different in enterprise vs community or what but the 
format the alfresco php library is sending a particular complexType is 
incorrect for our repository.

The 'nodes' choice of the cms:Predicate type needs to be a single 
array and the 'store' and 'uuid' elements be in another array inside 
of the nodes array.

I don't know if I got all of them but I found the problem in three 
places within the alfresco php library, attached are the sections of 
code in their fixed state.

I'm not really sure how this would be working for anyone unless the 
version of php soap we have serializes into XML differently than other 
peoples, not sure why that would be though.

```

Original issue reported on code.google.com by `rwether...@gmail.com` on 25 Nov 2011 at 5:56

Attachments:
- [alfresco-php-library-fixes.txt](https://storage.googleapis.com/google-code-attachments/alfresco-php-sdk/issue-5/comment-0/alfresco-php-library-fixes.txt)
- [alfreso-php-library-fixes-2.txt](https://storage.googleapis.com/google-code-attachments/alfresco-php-sdk/issue-5/comment-0/alfreso-php-library-fixes-2.txt)

**Comment by ghost** [comment]
Repository no longer supported. Archiving repository and closing the tickets.
